# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
xcode_workspace: Example/CDAlertViewExample.xcworkspace
xcode_sdk: iphonesimulator10.0
xcode_scheme: CDAlertViewExample
podfile: Example/Podfile
on:
  repo: candostdagdeviren/CDAlertView
  tags: true
before_install:
- gem install cocoapods
- pod install --project-directory=Example
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage build --no-skip-current
script:
- set -o pipefail
- xcodebuild -version
- pod lib lint
